import { useState, type FormEvent } from 'react'
import type { UserProfile } from './auth'
import './Home.css'
const areas = [{ name: 'Personal', color: '#e77932', icon: '♙' }, { name: 'Work', color: '#d9348b', icon: '▣' }, { name: 'Family', color: '#ad52bd', icon: '♧' }, { name: 'Health', color: '#7854df', icon: '♡' }, { name: 'Social', color: '#258bce', icon: '✦' }, { name: 'Fitness', color: '#149c89', icon: '⌁' }]
type CalendarEvent = { id: string; title: string; date: string; start: number; end: number; area: string }
const dateKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`
const hourLabel = (hour: number) => `${hour % 12 || 12} ${hour < 12 ? 'AM' : 'PM'}`
export default function Home({ user, toggleTheme }: { user: UserProfile; toggleTheme: () => void }) {
  const [offset, setOffset] = useState(0)
  const [search, setSearch] = useState('')
  const [hidden, setHidden] = useState<string[]>([])
  const [creating, setCreating] = useState(false)
  const [selected, setSelected] = useState<CalendarEvent | null>(null)
  const [events, setEvents] = useState<CalendarEvent[]>(() => {
    try { return JSON.parse(sessionStorage.getItem(`khalendara-events-${user.id}`) || '[]') } catch { return [] }
  })
  const monday = new Date(); monday.setHours(0,0,0,0); monday.setDate(monday.getDate() - (monday.getDay()+6)%7 + offset*7)
  const days = Array.from({ length: 5 }, (_, i) => { const day = new Date(monday); day.setDate(day.getDate()+i); return day })
  const today = dateKey(new Date())
  const visible = events.filter(event => !hidden.includes(event.area) && event.title.toLowerCase().includes(search.toLowerCase()))
  const saveEvents = (next: CalendarEvent[]) => { setEvents(next); try { sessionStorage.setItem(`khalendara-events-${user.id}`, JSON.stringify(next)) } catch { /* In-memory events remain available. */ } }
  const createEvent = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const fields = new FormData(event.currentTarget)
    const start = Number(fields.get('start')); const end = Number(fields.get('end'))
    if (end <= start) { (event.currentTarget.elements.namedItem('end') as HTMLSelectElement).setCustomValidity('End time must be after start time.'); event.currentTarget.reportValidity(); return }
    saveEvents([...events, { id: crypto.randomUUID(), title: String(fields.get('title')).trim(), date: String(fields.get('date')), start, end, area: String(fields.get('area')) }]); setCreating(false)
  }
  return <div className="calendar-app">
    <aside className="calendar-sidebar"><a className="calendar-brand" href="/home"><span>▦</span>Khalendara<span className="brand-dot">.</span></a><div className="sidebar-body"><p className="nav-caption">YOUR SPACE</p><div className="nav-active">▦ <span>My calendar</span><span className="nav-count">{events.length}</span></div><p className="nav-caption">AREAS</p>{areas.map(area => <button key={area.name} className={`area-button ${hidden.includes(area.name) ? 'area-hidden' : ''}`} onClick={() => setHidden(hidden.includes(area.name) ? hidden.filter(name => name !== area.name) : [...hidden, area.name])} aria-pressed={!hidden.includes(area.name)}><span style={{ color: area.color }}>{area.icon}</span>{area.name}<span className="area-check" style={{ background: hidden.includes(area.name) ? 'transparent' : area.color }}>✓</span></button>)}<div className="sidebar-note"><span>✦</span><strong>A little space for your everyday.</strong><p>Make room for what matters, one day at a time.</p></div></div><div className="sidebar-profile"><span className="avatar">{user.firstName[0]}{user.lastName[0]}</span><div><strong>{user.firstName} {user.lastName}</strong><small>{user.email}</small></div></div></aside>
    <main className="calendar-main"><header className="calendar-topbar"><label className="calendar-search"><span aria-hidden="true">⌕</span><input aria-label="Search events" placeholder="Search your calendar…" value={search} onChange={event => setSearch(event.target.value)}/><kbd>⌕</kbd></label><button className="calendar-button theme-button" onClick={toggleTheme} aria-label="Toggle color theme">◐</button><span className="topbar-avatar avatar" title={`${user.firstName} ${user.lastName}\n${user.email}`}>{user.firstName[0]}{user.lastName[0]}</span></header>
    <section className="calendar-heading"><div><p className="eyebrow">YOUR TIME, YOUR PACE</p><h1>Make space for a good week<span>.</span></h1><p>Welcome back, {user.firstName}. A little clarity goes a long way.</p></div><button className="new-event-button" onClick={() => setCreating(true)}>＋ New event</button></section>
    <div className="calendar-toolbar"><div className="week-controls"><button className="calendar-button" onClick={() => setOffset(0)}>Today</button><div className="week-arrows"><button aria-label="Previous week" onClick={() => setOffset(offset-1)}>‹</button><button aria-label="Next week" onClick={() => setOffset(offset+1)}>›</button></div><h2>{days[0].toLocaleDateString(undefined,{month:'short',day:'numeric'})} – {days[4].toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</h2></div><div className="calendar-meta"><span>{Intl.DateTimeFormat().resolvedOptions().timeZone.replaceAll('_',' ')}</span><span className="view-badge">Weekdays</span></div></div>
    <div className="calendar-scroll"><div className="week-calendar"><div className="day-headers"><div className="time-zone">GMT{ -new Date().getTimezoneOffset()/60 >= 0 ? '+' : ''}{-new Date().getTimezoneOffset()/60}</div>{days.map(day => <div className={`day-header ${dateKey(day) === today ? 'is-today' : ''}`} key={dateKey(day)}><span>{day.toLocaleDateString(undefined,{weekday:'short'})}</span><strong>{day.getDate()}</strong>{dateKey(day) === today && <small>TODAY</small>}</div>)}</div><div className="calendar-grid"><div className="hour-column">{Array.from({length:11},(_,i)=><div key={i}>{hourLabel(i+8)}</div>)}</div>{days.map(day=><div className="day-column" key={dateKey(day)}>{Array.from({length:11},(_,i)=><div className="hour-cell" key={i}/>)}{visible.filter(event=>event.date===dateKey(day)).map(event => { const area = areas.find(area=>area.name===event.area)!; return <button className="event-card" key={event.id} style={{ top: (event.start-8)*72+5, height: (event.end-event.start)*72-10, borderColor: area.color, background: `color-mix(in srgb, ${area.color} 9%, var(--color-surface))` }} onClick={()=>setSelected(event)}><strong>{event.title}</strong><span>{hourLabel(event.start)} – {hourLabel(event.end)}</span><small style={{color:area.color}}>{event.area}</small></button> })}</div>)}</div></div></div>
    <footer className="calendar-footer"><span><i/> All caught up. Your time is yours.</span><span>Events are saved in this browser session.</span></footer></main>
    {(creating || selected) && <div className="modal-backdrop" onClick={()=>{setCreating(false);setSelected(null)}}><section className="event-modal" role="dialog" aria-modal="true" aria-labelledby="event-title" onClick={event=>event.stopPropagation()} onKeyDown={event=>{if(event.key==='Escape'){setCreating(false);setSelected(null)}}}><button className="close-modal" aria-label="Close dialog" onClick={()=>{setCreating(false);setSelected(null)}}>×</button><p className="eyebrow">MAKE ROOM FOR WHAT MATTERS</p><h2 id="event-title">{selected ? selected.title : 'A little plan for your day'}</h2>{selected ? <><p>{selected.date} · {hourLabel(selected.start)} – {hourLabel(selected.end)}</p><p>{selected.area}</p><button className="calendar-button" onClick={()=>{saveEvents(events.filter(event=>event.id!==selected.id));setSelected(null)}}>Delete event</button></> : <form onSubmit={createEvent}><label>Event name<input autoFocus name="title" className="field" required maxLength={100} pattern=".*\S.*" placeholder="What are you making time for?"/></label><label>Date<input className="field" name="date" type="date" defaultValue={dateKey(days[0])} required/></label><div className="event-times">{['start','end'].map(name=><label key={name}>{name==='start'?'Starts':'Ends'}<select name={name} defaultValue={name==='start'?9:10} onChange={event=>event.currentTarget.setCustomValidity('')}>{Array.from({length:name==='start'?11:11},(_,i)=><option key={i} value={i+(name==='start'?8:9)}>{hourLabel(i+(name==='start'?8:9))}</option>)}</select></label>)}</div><label>Area<select name="area">{areas.map(area=><option key={area.name}>{area.name}</option>)}</select></label><p className="event-disclaimer">Saved in this browser session. Calendar sync is not connected yet.</p><button className="new-event-button" type="submit">Create event</button></form>}</section></div>}
  </div>
}
