spring.application.name=Khalendara

spring.datasource.url=jdbc:postgresql://localhost:5323/khalendara
spring.datasource.username=manjama
spring.datasource.password=password

jwt.secret=a9zOL7m7GoR76U2F1Hvw8ja0irdVa04O1L6R408JF4a9zOL7m7GoR76U2F1Hvw8ja0irdVa04O1L6R408JF4

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
#-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect